version: "3.5"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elastic
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - elastic-network

volumes:
  elastic-data:
    name: 'elastic-data'
    driver: local

networks:
  elastic-network:
    name: 'elastic-network'
    driver: bridge
